### ISSUE TITLE
Error building: "Cannot open file, path = '/usr/lib/dart/lib/_internal/ddc_sdk.sum'

### ISSUE THREAD

**Issue by Meai1** [polymer-dart/html5_demo#1]
The setting you told me about doesnt seem to actually be applied, it's still looking in the /usr/lib location

```
[pc@localhost html5_demo]$ polymerize init --dart-bin-path=/home/pc/Desktop/dart-sdk/bin
SDK : Directory: '/home/pc/Desktop/dart-sdk/bin'
[pc@localhost html5_demo]$ bazel build html5_demo
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/pc/.cache/bazel/_bazel_pc/4fd34575ce08b07729b6c22ac54becca/external/js/BUILD:8:1: Polymerizing ../js/js.js failed: polymerize failed: error executing command bazel-out/host/bin/external/polymerize_tool/polymerize -o /tmp/out bazel -s external/js/lib/js.dart -s external/js/lib/js_util.dart -s external/js/lib/src/varargs.dart -T ... (remaining 17 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 255.
Unhandled exception:
FileSystemException: Cannot open file, path = '/usr/lib/dart/lib/_internal/ddc_sdk.sum' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:562)
#1      _File.openSync (dart:io/file_impl.dart:413)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:473)
#3      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:410)
#4      List.forEach (dart:core-patch/growable_array.dart:258)
#5      SummaryDataStore.SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:327)
#6      SummaryBasedDartSdk.SummaryBasedDartSdk (package:analyzer/src/summary/summary_sdk.dart:41)
#7      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:320)
#8      ModuleCompiler.ModuleCompiler (package:dev_compiler/src/compiler/compiler.dart:83)
#9      _buildOne.<_buildOne_async_body> (package:polymerize/polymerize.dart:251)
#10     _RootZone.runUnary (dart:async/zone.dart:1404)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#13     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#14     _Future._completeWithValue (dart:async/future_impl.dart:477)
#15     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
Target //:html5_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.100s, Critical Path: 0.38s
```

**Comment by dam0vm3nt** [comment]
Oh! One step further. You are right there's another place where it needs the SDK path. Need to fix that too.

**Comment by dam0vm3nt** [comment]
k. now it should work. Sorry but I can't easily reproduce your environment, so I must ask you to test it.

Again : 
 - do a `pub global activate polymerize` to update to `0.4.7`
 - and a `polymerize init` on  the project

then retry the build : `bazel build html5_demo`.

I expect to work or at least to change the error.

I hope that that warning about the build not being sandbox doesn't change the result anyway.

Let me know.

**Comment by dam0vm3nt** [comment]
Please reopen it if it still doesn't work. tnx.
